### ISSUE TITLE
Improve information about how to run the test

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sensorml10#3]
We should have two options:

1) Provide a URL
2) Upload file to be tested

For the first option we should clarify that the URL can be

- an SOS 2.0 DescribeSensor request (The root element is ...). For example
- an SOS 1.0 DescribeSensor request (The root element is ...) , For example
- a SensorML with a public URL ( The root element is ...). For example ( Maybe an example from the GitHub repository)

For the second option, in similar way clarify what type of files can be submitted.

**Comment by rockygis** [comment]
I have update some example to sensorML 1.0.1, whickh look like img below:

![image](https://cloud.githubusercontent.com/assets/6157282/6723551/9b8a7040-ce24-11e4-8200-ec0b7766e618.png)
