### ISSUE TITLE
Check status of test

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sensorml10#4]
Check that test:

- is complete related to conformance classes detailed in the standard and documented in the project documentation (site folder)
- pass with reference implementation (52 North)

http://sensorweb.demo.52north.org/52n-sos-webapp/client

**Comment by rockygis** [comment]
There are no Req or test method in SensorML 1.0.0 (07-000) or 1.0.1 (07-122r2) , so we only test the schema of sensorml.

Here is the result of test:(All Pass)
Test 1: SensorML Xml
URL: https://raw.githubusercontent.com/opengeospatial/ets-sensorml10/master/src/main/example/SensorML1.0.1.xml
![sensorml_1](https://cloud.githubusercontent.com/assets/6157282/9266686/25016f88-4277-11e5-88f9-a50bff7a98bd.png)

Test 2: DescribeSensorResponse
URL:http://sensorweb.demo.52north.org/52n-sos-webapp/sos/kvp?request=DescribeSensor&service=SOS&version=2.0.0&procedure=http://www.52north.org/test/procedure/9&procedureDescriptionFormat=http://www.opengis.net/sensorML/1.0.1
![sensorml_2](https://cloud.githubusercontent.com/assets/6157282/9266701/61b7e0ba-4277-11e5-93a9-2a728a137371.png)
